services:

  loadbalancer:
    build: loadbalancer
    ports:
      - "8000:80"

  webserver1:
    build: webserver1
    ports: 
      - 8080:80

  webserver2:
    build: webserver2
    ports: 
      - 8081:80
